apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-2ft2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-2ft2
    app.kubernetes.io/part-of: test-app-vtpj
  name: devfile-sample-python-basic-2ft2
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-2ft2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-2ft2
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-vrqz-tenant/test-app-vtpj/devfile-sample-python-basic-2ft2@sha256:55944286fec1a718796e46ade9c066823f8d58ff3d10736634d72e1d9b83aa6a
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
